### ISSUE TITLE
关于资料库的同步与更新

### ISSUE THREAD

**Issue by hooke007** [Protostars/KikoPlay#11]
将媒体文件拖入播放列表后，关联弹幕池难免会产生识别错误，然后这个错误信息也一并被记录入资料库了。

在播放列表中重新关联正确后，资料库不会修正过来，不知将来有意加入将二者资料进行同步、统一的功能。

**Comment by Protostars** [comment]
直接在资料库里重新搜索就可以了

**Comment by hooke007** [comment]
额，虽然手动一条条重新关联是可行，但是这个工作量好大......

**Comment by Protostars** [comment]
其实资料库就是记录你看过的动画，有错误的话在右键菜单 “获取详细信息” 里重新搜索一下
你添加了多少动画啊。。。。

**Comment by hooke007** [comment]
不是，是“动画信息”里边的“剧集”里边存在大量错误，只能删掉导入视频再一个个改

**Comment by Protostars** [comment]
是标题不对还是关联的动画不对？

**Comment by hooke007** [comment]
这个怎么说呢，播放列表在关联弹幕池的时候识别成的别的动画，然后资料库就把这个错误的标题写进去了

**Comment by Protostars** [comment]
哦哦，你直接把那个动画删了，之后在列表里手动关联到正确的动画
“剧集”页面里，双击标题是可以直接修改的，此外，可以试试按下“获取剧集标题”按钮，之后双击标题，下拉列表里就是从bangumi上获取的标题，可直接选择

**Comment by hooke007** [comment]
我确实是这样一个一个弄过去的..........

**Comment by Protostars** [comment]
下个版本会做些改进（大概。。现在并不清楚下个版本会什么时候发布）

**Comment by liuye1992** [comment]
> 下个版本会做些改进（大概。。现在并不清楚下个版本会什么时候发布）

我想问下，如何添加三次元媒体的动画信息？可以设计一个界面直接输入该媒体所对应的bangumi番号来解决么？

如果你们没有时间做，能不能告诉我修改哪一段代码即可，我想现在的问题应该是当初设计只涵盖bangumi收录的动漫所导致的。

**Comment by Protostars** [comment]
> 
> 
> > 下个版本会做些改进（大概。。现在并不清楚下个版本会什么时候发布）
> 
> 我想问下，如何添加三次元媒体的动画信息？可以设计一个界面直接输入该媒体所对应的bangumi番号来解决么？
> 
> 如果你们没有时间做，能不能告诉我修改哪一段代码即可，我想现在的问题应该是当初设计只涵盖bangumi收录的动漫所导致的。

KikoPlay就是为了看动画而设计的，在```UI/bangumisearch.cpp```， ```BangumiSearch::search```函数里，你可以将```query.addQueryItem("type","2");```这句对搜索结果的限制取消掉，这样就能搜出其他条目

**Comment by liuye1992** [comment]
> > > 下个版本会做些改进（大概。。现在并不清楚下个版本会什么时候发布）
> > 
> > 
> > 我想问下，如何添加三次元媒体的动画信息？可以设计一个界面直接输入该媒体所对应的bangumi番号来解决么？
> > 如果你们没有时间做，能不能告诉我修改哪一段代码即可，我想现在的问题应该是当初设计只涵盖bangumi收录的动漫所导致的。
> 
> KikoPlay就是为了看动画而设计的，在`UI/bangumisearch.cpp`， `BangumiSearch::search`函数里，你可以将`query.addQueryItem("type","2");`这句对搜索结果的限制取消掉，这样就能搜出其他条目

哦好的 非常感谢

**Comment by liuye1992** [comment]
> > > 下个版本会做些改进（大概。。现在并不清楚下个版本会什么时候发布）
> > 
> > 
> > 我想问下，如何添加三次元媒体的动画信息？可以设计一个界面直接输入该媒体所对应的bangumi番号来解决么？
> > 如果你们没有时间做，能不能告诉我修改哪一段代码即可，我想现在的问题应该是当初设计只涵盖bangumi收录的动漫所导致的。
> 
> KikoPlay就是为了看动画而设计的，在`UI/bangumisearch.cpp`， `BangumiSearch::search`函数里，你可以将`query.addQueryItem("type","2");`这句对搜索结果的限制取消掉，这样就能搜出其他条目

请教一下，用QT编译的framelesswindos.cpp的时候，出现了头文件缺失的错误，是怎么回事？是本身下载的文件缺失还是其他问题？

![QQ图片20190811185301](https://user-images.githubusercontent.com/50910435/62832466-78748180-bc69-11e9-868a-b183e9635cb1.png)

![QQ图片20190811185315](https://user-images.githubusercontent.com/50910435/62832467-790d1800-bc69-11e9-9c0f-e0f082f8ab6c.png)

**Comment by Protostars** [comment]
这是Windows SDK里的头文件，你需要安装它
比如，在我的机器里，这几个头位于C:\Program Files (x86)\Windows Kits\8.1\Include\um\目录中
还有，我编译KikoPlay在Windows上用的是MSVC 2015，同时现在只编译64位版本，不建议编译32位

**Comment by liuye1992** [comment]
> 这是Windows SDK里的头文件，你需要安装它
> 比如，在我的机器里，这几个头位于C:\Program Files (x86)\Windows Kits\8.1\Include\um\目录中
> 还有，我编译KikoPlay在Windows上用的是MSVC 2015，同时现在只编译64位版本，不建议编译32位

能加qq群聊吗？我前天加入你们群好像没有回应。

**Comment by Protostars** [comment]
> 
> 
> > 这是Windows SDK里的头文件，你需要安装它
> > 比如，在我的机器里，这几个头位于C:\Program Files (x86)\Windows Kits\8.1\Include\um\目录中
> > 还有，我编译KikoPlay在Windows上用的是MSVC 2015，同时现在只编译64位版本，不建议编译32位
> 
> 能加qq群聊吗？我前天加入你们群好像没有回应。

QQ群就是README里写的那个群

**Comment by Protostars** [comment]
现在重新关联之后资料库中的标题也会同步
