### ISSUE TITLE
彈幕顯示不正常

### ISSUE THREAD

**Issue by MononeV** [Protostars/KikoPlay#12]
![image](https://user-images.githubusercontent.com/39477101/64924364-f06d3300-d837-11e9-9559-fa4adc01c636.png)
![image](https://user-images.githubusercontent.com/39477101/64924550-1267b500-d83a-11e9-974b-e839d363264f.png)
請問彈幕出來頭幾個字顯示不正常還會一直閃，是什麼問題？
OS Windows 10 1903
顯卡驅動 Radeon Adrenalin 19.5.2
mpv默認設置

**Comment by Protostars** [comment]
似乎是显卡的问题，修改一下设置试试：
在data/settings.ini文件的Play组下，加上一句：
Sampler2DArray=false

**Comment by MononeV** [comment]
OK了
所以這是A卡的問題？

**Comment by Protostars** [comment]
差不多吧
