### ISSUE TITLE
【建议】不同的用户使用自己的观看记录

### ISSUE THREAD

**Issue by pureboys** [Protostars/KikoPlay#13]
在群友 sanbikappa 讨论时发现。 KikoPlay运行是会在当前目录生成一个配置文件夹 data， 这个文件夹里存放了弹幕和观看记录信息。在linux环境下，能不能把这个文件夹放到用户的家目录里，建一个.kikoplay的配置文件夹，把data文件夹放到这个配置文件夹里， 用户在运行时，如果配置文件存在，则加载这个配置文件，不存在时，在家目录下新建一个。这样的话。每个用户都能创建自己的观看记录了。

**Comment by Protostars** [comment]
要是想修改data目录的位置的话，倒是比较简单
在```globalobjects.cpp```文件中，```void GlobalObjects::init()```函数的第一行：
```
dataPath=QCoreApplication::applicationDirPath()+"/data/";
```
你自己改成别的目录，之后重新编译就可以了
