### ISSUE TITLE
安装不上 编译错误

### ISSUE THREAD

**Issue by lowy** [Protostars/KikoPlay#15]
系统：manjaro
软件版本：0.6
开始是直接在aur源里安装 失败之后源码clone编译安装 同样失败 两者都出现了相同的如下错误提示：
Play/Danmu/Provider/iqiyiprovider.cpp: 在成员函数‘void IqiyiProvider::decodeDanmu(const QByteArray&, QList<DanmuComment*>&)’中:
Play/Danmu/Provider/iqiyiprovider.cpp:217:10: 警告：变量‘dmStart’被设定但未被使用 [-Wunused-but-set-variable]
  217 |     bool dmStart=false;
      |          ^~~~~~~
Play/Danmu/Provider/iqiyiprovider.cpp: 在成员函数‘int IqiyiProvider::decompress(const QByteArray&, QByteArray&)’中:
Play/Danmu/Provider/iqiyiprovider.cpp:294:21: 警告：this statement may fall through [-Wimplicit-fallthrough=]
  294 |                 ret = Z_DATA_ERROR;
Play/Danmu/Provider/iqiyiprovider.cpp:295:13: 附注：here
  295 |             case Z_DATA_ERROR:
      |             ^~~~
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DZLIB_WINAPI -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -IPlay/Video -ILANServer -IDownload/Script/lua -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o flowlayout.o Common/flowlayout.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DZLIB_WINAPI -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -IPlay/Video -ILANServer -IDownload/Script/lua -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o animedetailinfo.o UI/animedetailinfo.cpp
In file included from UI/animedetailinfo.cpp:1:
UI/animedetailinfo.h:33:33: 错误：field ‘tagList’ has incomplete type ‘QMap<QString, QPushButton*>’
   33 |     QMap<QString,QPushButton *> tagList;
      |                                 ^~~~~~~
In file included from /usr/include/qt/QtCore/qglobal.h:1290,
                 from /usr/include/qt/QtCore/qsystemdetection.h:42,
                 from UI/framelessdialog.h:4,
                 from UI/animedetailinfo.h:4,
                 from UI/animedetailinfo.cpp:1:
/usr/include/qt/QtCore/qtypeinfo.h:240:1: 附注：declaration of ‘class QMap<QString, QPushButton*>’
  240 | Q_DECLARE_MOVABLE_CONTAINER(QMap);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:2277：animedetailinfo.o] 错误 1

**Comment by Protostars** [comment]
Qt版本是多少？
之前试过在manjaro上编译，看[这里](https://github.com/Protostars/KikoPlay/issues/8)
当时的版本是5.12.3，KikoPlay 0.6.0可以编译成功

**Comment by lowy** [comment]
5.14.0 哦 是我滚得比较勤 需要回滚吗

**Comment by Protostars** [comment]
回到5.12.3试试？我没有在更高的Qt版本上试过编译
