### ISSUE TITLE
尝试添加Anime4K但没效果，请问能提供支持吗

### ISSUE THREAD

**Issue by wdw89** [Protostars/KikoPlay#16]
Anime4K是个插值滤镜，通过glsl支持mpv，测试了2.0rc和1.0rc2都无法生效，2.0版在原版mpv里亲测能生效的设置说明https://github.com/bloc97/Anime4K/issues/62
我有把这里提到的glsl文件名替换为实际的文件名

**Comment by Protostars** [comment]
在MPV参数设置里：
```
glsl-shaders=F:\Projects\KikoPlay_Release\glsl\Anime4K_Hybrid_v2.0RC.glsl
```
类似这样应该是可以正常加载的，后面不用加双引号

**Comment by wdw89** [comment]
谢谢，真的是去掉引号就可以了

**Comment by moomiji** [comment]
**版本0.9.0**
顺便一提，MPV快捷键（非按键直传模式）中MPV命令中，想要做到`change-list glsl-shaders set`应该类似如下填写：
```
# 去除换行
no-osd change-list glsl-shaders clr "";
no-osd change-list glsl-shaders append D:\ProgramData\MPV_lazy\shaders\Anime4K_Clamp_Highlights.glsl;
……
no-osd change-list glsl-shaders append D:\ProgramData\MPV_lazy\shaders\Anime4K_Upscale_CNN_x2_S.glsl
```

建议看使用说明，打开`按键直传模式`使用快捷键，注意 input.conf 文件中的所有路径改为如下形式：`D:\\ProgramData\\MPV_lazy\\shaders\\Anime4K_Clamp_Highlights.glsl`

**Comment by rakaki** [comment]
> **版本0.9.0** 顺便一提，MPV快捷键（非按键直传模式）中MPV命令中，想要做到`change-list glsl-shaders set`应该类似如下填写：
> 
> ```
> # 去除换行
> no-osd change-list glsl-shaders clr "";
> no-osd change-list glsl-shaders append D:\ProgramData\MPV_lazy\shaders\Anime4K_Clamp_Highlights.glsl;
> ……
> no-osd change-list glsl-shaders append D:\ProgramData\MPV_lazy\shaders\Anime4K_Upscale_CNN_x2_S.glsl
> ```
> 
> **建议看使用说明，打开`按键直传模式`使用快捷键**，注意 input.conf 文件中的所有路径改为如下形式：`D:\\ProgramData\\MPV_lazy\\shaders\\Anime4K_Clamp_Highlights.glsl`

感谢，这么做的话确实可以使用
