### ISSUE TITLE
【功能建议】进度条缩略图&章节标记支持

### ISSUE THREAD

**Issue by hooke007** [Protostars/KikoPlay#17]
[<a href="https://sm.ms/image/1jRlCUKYvkyb4No" target="_blank"><img src="https://i.loli.net/2020/04/11/1jRlCUKYvkyb4No.jpg" alt="Snipaste_2020-04-11_16-42-45.jpg"></a>](url)
章节标记这个原版mpv就是支持的。
进度条预览我是mpv用mpv_thumbnail_script_server脚本实现，但是并不能在kiko中启用（而且这个脚本在mpv中也过于吃处理器性能且经常出错）希望能额外的进度条预览图支持。

**Comment by Protostars** [comment]
之后可以考虑，近期太忙没有时间

**Comment by Protostars** [comment]
已支持
