### ISSUE TITLE
macOS 编译结果 播放界面存在问题

### ISSUE THREAD

**Issue by wooddance** [Protostars/KikoPlay#19]
在安装了相关库和修改了 KikoPlay.pro 文件后成功编译了，是程序界面上存在一些问题。
1. 播放画面过小，无论是窗口缩放多大或者是全屏，播放画面都是固定大小在左下角
![](https://i.loli.net/2020/04/22/4IsCWOy5XGqMTBR.png)

2. 视频标题栏部分竖直方向上显示不全
![](https://i.loli.net/2020/04/22/9AuTLYw63SDCaiE.png)

3. 编译出的 Application 没有图标

**Comment by Protostars** [comment]
可能macOS的窗口系统和windows或者linux有点区别，类似[这样](https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window/issues/9)，不过我现在没有macOS设备，这个问题目前暂时无解

**Comment by Protostars** [comment]
问题1，2在最新的代码中应该已经解决
问题3，macOS上你可以自己试试制作icns文件，之后在pro文件中加上`ICON = xxx.icns`
