### ISSUE TITLE
error: creating ssl context

### ISSUE THREAD

**Issue by lpl2002** [Protostars/KikoPlay#2]
已下载libssl.zip并解压到根目录下
并重启程序依然报错
![ttt](https://user-images.githubusercontent.com/23260072/46535164-19254280-c8dd-11e8-97da-bc5cc72f386f.png)

**Comment by Protostars** [comment]
是在下载哪个网站的弹幕？

**Comment by lpl2002** [comment]
> 是在下载哪个网站的弹幕？

关联弹幕池的时候就.,...

**Comment by Protostars** [comment]
> 
> 
> > 是在下载哪个网站的弹幕？
> 
> 关联弹幕池的时候就.,...

这都是Qt程序使用https的问题，之前贴吧也有人反馈过这个问题，不过是在搜索弹幕时出现的（Bilibili等网站都是https，关联时弹弹API也是），把Open SSL那三个dll放到程序同一目录下就能解决问题
我刚刚在一个纯净的win7 上测试了一下，放入三个dll之后就可以正常关联和搜索弹幕了
╮(╯-╰)╭

**Comment by lpl2002** [comment]
我现在从学校回家。。等我到家用家里电脑试试

**Comment by lpl2002** [comment]
经测试。
学校win10 x64 1809 动漫OneRoom第二季 （Nyaa下载的）。无法关联弹幕池/下载字幕
家里win10 x64 LTSC2019 动漫SlowStart一切正常。
