### ISSUE TITLE
能否增加一个类似“弹弹play展会版”那样的透明播放弹幕的功能？

### ISSUE THREAD

**Issue by Jianfeng-Du** [Protostars/KikoPlay#22]
能否增加一个类似“弹弹play展会版”那样的透明播放弹幕的功能？

不播放视频，只使用一个透明层来播放弹幕，这样可以将弹幕叠加到任意网页的视频上。就像透明播放歌词那样的效果。

弹弹play展会版的免费账号有 15 分钟的限制，[反馈](https://support.qq.com/products/104929/post/158842033595453198/)给他们后，似乎并不打算添加 (｡╯︵╰｡)。要是这个播放器能支持就好了

**Comment by Protostars** [comment]
这功能对于KikoPlay没有意义，不会加
不过你可以看看[这个](https://github.com/xqq/libwtfdanmaku)

**Comment by Jianfeng-Du** [comment]
好的，谢谢，我看看
