### ISSUE TITLE
能提供下mpv在windows下的编译的方法吗

### ISSUE THREAD

**Issue by wxz879526** [Protostars/KikoPlay#28]
能提供下mpv在windows下的编译的方法吗

**Comment by Protostars** [comment]
我直接用了编译好的[libmpv](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/)

**Comment by zj951555793** [comment]
> 我直接用了编译好的[libmpv](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/)

这个没有 debug版本的
