### ISSUE TITLE
Manjaro系统下看视频时 受系统电源管理限制

### ISSUE THREAD

**Issue by Od1gree** [Protostars/KikoPlay#29]
在看视频的过程中, 电脑无操作时间达到电源管理`锁屏`及`关闭屏幕`的时间阈值时, 会执行相应的操作, 此时视频及声音照常播放, 移动鼠标唤醒电脑后恢复正常.

目前我使用`caffeine-ng`来阻止电源管理器执行`锁屏`及`关闭屏幕`的操作.

我的系统设置信息如下:
* OS: Manjaro 20.1 Mikah
* Kernel: x86_64 Linux 5.7.14-1-MANJARO
* DE: KDE 5.73.0 / Plasma 5.19.4
* 电源管理工具: TLP 1.3.1-2 

软件版本如下:
* kikoplay 0.7.1-1 (从AUR源安装)
* mpv 1:0.32.0

**Comment by Protostars** [comment]
windows上在播放视频时会阻止关闭屏幕，其他平台目前没有做特殊处理
