### ISSUE TITLE
无中文

### ISSUE THREAD

**Issue by Summer1Solstice** [Protostars/KikoPlay#30]
![捕获1](https://user-images.githubusercontent.com/46267607/91654433-281dcb00-eadb-11ea-8bfc-ad6379a2027a.JPG)

**Comment by Protostars** [comment]
试试最新的0.7.2看是否存在这个问题

**Comment by Summer1Solstice** [comment]
最新版还是显示英文
![00](https://user-images.githubusercontent.com/46267607/96429105-25199e00-1233-11eb-9158-2f84dac78937.JPG)

**Comment by Protostars** [comment]
下载这个小程序，放到KikoPlay目录下运行，显示的是什么？
链接: https://pan.baidu.com/s/1fZwaYWZ6OMGM3eMIqI3CgA 提取码: 3s93

**Comment by Summer1Solstice** [comment]
就一个字母"c"
![00](https://user-images.githubusercontent.com/46267607/96678913-38e51180-13a5-11eb-921a-d77705fbe9e8.JPG)

**Comment by Protostars** [comment]
正常情况下简体中文系统应该显示zh_CN，不太清楚这个情况
不过我更新了一下百度云的0.7.2，你可以下载之后，修改data/settings.ini，增加下面的内容来选择中文：
```
[KikoPlay]
Language=zh_cn
```

**Comment by Summer1Solstice** [comment]
ok了

**Comment by Summer1Solstice** [comment]
重启一下，可能找到问题的原因了。
今天给Cheat Engine设置中文的时候，明明汉化包位置对，但是设置语言为“zh_CN"后重启CE就会变成"English"。
翻看官网语言设置相关，注意到默认语言设置是根据系统语言的变量设置的。
查看我系统中的LANG变量，值是”CHS“。
猜测问题的根源是win10系统变量的问题.
验证猜测:移除"data / settings.ini",LANG变量:"zh_CN".
![验证成功](https://user-images.githubusercontent.com/46267607/107115974-43bba780-68ab-11eb-8460-73d327d55577.JPG)
逆向重现:LANG变量:"CHS".
![逆向重现成功](https://user-images.githubusercontent.com/46267607/107115987-5e8e1c00-68ab-11eb-9568-6e5d8e6683e8.JPG)
(完)
