### ISSUE TITLE
aria2参数 及最小化托盘

### ISSUE THREAD

**Issue by underlaw** [Protostars/KikoPlay#32]
你好
软件点x后完全退出了，不能后台下载。
请问aria2参数会不会和软件内置参数冲突?如冲突要注意什么

**Comment by underlaw** [comment]
RPC Reply Error: aria2.getPeers
全局日志显示，RPC不是连接设置吗 aria2.getPeers这大概意思是得到peers，这合在一起是什么意思了。
下面是我加的参数，去掉了下载路径 RPC相关 做种时间  同时下载任务数，怕和软件参数冲突
disk-cache=32M
continue=true
file-allocation=falloc
max-connection-per-server=16
max-overall-download-limit=0
max-download-limit=0
max-overall-upload-limit=300K
max-upload-limit=100K
disable-ipv6=true
min-split-size=1M
split=16
check-certificate=false
save-session-interval=5
follow-torrent=true
peer-agent=Transmission/3.00
peer-id-prefix=-TR3000-
force-save=false
bt-seed-unverified=true
bt-save-metadata=true
check-integrity=false
max-tries=0
enable-http-pipelining=true
bt-remove-unselected-file=true
bt-metadata-only=false
bt-min-crypto-level=plain
bt-require-crypto=true
bt-request-peer-speed-limit=500K
bt-stop-timeout=0
bt-tracker-connect-timeout=60
bt-tracker-interval=0
bt-tracker-timeout=60
enable-peer-exchange=true
pause-metadata=false
rpc-save-upload-metadata=true
allow-overwrite=false
allow-piece-length-change=true
always-resume=true
async-dns=true
auto-file-renaming=true
conditional-get=false
content-disposition-default-utf8=false
download-result=default
enable-mmap=false
save-not-found=false
hash-check-only=false
keep-unfinished-download-result=true
max-download-result=1000
max-mmap-limit=9223372036854775807
max-resume-failure-tries=0
log-level=debug
optimize-concurrent-downloads=true
piece-length=10M
no-file-allocation-limit=10M
parameterized-uri=false
realtime-chunk-checksum=false
remove-control-file=false
bt-enable-hook-after-hash-check=false
bt-enable-lpd=true
bt-force-encryption=false
bt-hash-check-seed=false
bt-load-saved-metadata=true
bt-max-peers=0
enable-dht=true
enable-dht6=false
dht-file-path=c:/Users/zh.w/.cache/aria2/dht.dat
user-agent=Mozilla / 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 84.0.4147.105 Safari / 537.36
stream-piece-selector=inorder
uri-selector=adaptive
use-head=true
referer=*

**Comment by Protostars** [comment]
点关闭之后程序会完全退出，如果要下载就不要关闭
aria2参数基本上不会和内置参数有冲突，RPC Reply Error一般没什么问题，getPeers只有在bt下载的时候才有效，其他类型的任务可能会返回错误
KikoPlay在启动aria2时会设置两个参数：
```
args << "--enable-rpc=true";
args << "--rpc-listen-port=6800";
```
在添加链接任务时会设置这些参数：
```c++
options.insert("dir", dir);
options.insert("bt-metadata-only","true");
options.insert("bt-save-metadata","true");
options.insert("seed-time", QString::number(GlobalObjects::appSetting->value("Download/SeedTime", 5).toInt()));
options.insert("bt-tracker", GlobalObjects::appSetting->value("Download/Trackers", QStringList()).toStringList().join(','));
```
在添加种子时会设置这些参数：
```
options.insert("dir", dir);
options.insert("select-file",selIndexes);
options.insert("seed-time",QString::number(GlobalObjects::appSetting->value("Download/SeedTime",5).toInt()));
options.insert("bt-tracker",GlobalObjects::appSetting->value("Download/Trackers",QStringList()).toStringList().join(','));
```
以上基本上都是和任务相关的一些参数，在外部设置了别的应该会被覆盖掉
总之基本上和外部的参数不会有什么冲突

**Comment by underlaw** [comment]
> 点关闭之后程序会完全退出，如果要下载就不要关闭
> aria2参数基本上不会和内置参数有冲突，RPC Reply Error一般没什么问题，getPeers只有在bt下载的时候才有效，其他类型的任务可能会返回错误
> KikoPlay在启动aria2时会设置两个参数：
> 
> ```
> args << "--enable-rpc=true";
> args << "--rpc-listen-port=6800";
> ```
> 
> 在添加链接任务时会设置这些参数：
> 
> ```c++
> options.insert("dir", dir);
> options.insert("bt-metadata-only","true");
> options.insert("bt-save-metadata","true");
> options.insert("seed-time", QString::number(GlobalObjects::appSetting->value("Download/SeedTime", 5).toInt()));
> options.insert("bt-tracker", GlobalObjects::appSetting->value("Download/Trackers", QStringList()).toStringList().join(','));
> ```
> 
> 在添加种子时会设置这些参数：
> 
> ```
> options.insert("dir", dir);
> options.insert("select-file",selIndexes);
> options.insert("seed-time",QString::number(GlobalObjects::appSetting->value("Download/SeedTime",5).toInt()));
> options.insert("bt-tracker",GlobalObjects::appSetting->value("Download/Trackers",QStringList()).toStringList().join(','));
> ```
> 
> 以上基本上都是和任务相关的一些参数，在外部设置了别的应该会被覆盖掉
> 总之基本上和外部的参数不会有什么冲突

感谢回复，不过bt下载基本上是长时间的,点x最小化到托盘还是很有必要的，望采纳
