### ISSUE TITLE
关于日剧的资料

### ISSUE THREAD

**Issue by mikusaa** [Protostars/KikoPlay#35]
日剧在bgm的资料完全没法搜到……
![](https://user-images.githubusercontent.com/31799398/99144381-59e90b80-26a0-11eb-8c98-e01593711a6f.png)
能否添加一个手动输入id的功能呢？
![](https://user-images.githubusercontent.com/31799398/99144419-b1877700-26a0-11eb-95e7-e669f663ac9d.png)

**Comment by Protostars** [comment]
搜索的时候程序会进行过滤，只保留动画的结果，因此不会有其他类型的条目

**Comment by Protostars** [comment]
0.8资料通过外置脚本实现，目前可以支持搜索其他类型的条目

**Comment by mikusaa** [comment]
> 0.8资料通过外置脚本实现，目前可以支持搜索其他类型的压缩

好耶！感谢！！
