### ISSUE TITLE
对于完全不懂这块的 manjaro 用户有点难啊

### ISSUE THREAD

**Issue by pureboys** [Protostars/KikoPlay#8]
能提供下 arch/manjaro 下小白的编译方法么, 动手一步步的教程， 下载下来的 ubuntu 版本直接运行缺少库，google了错误但是，还是不知道怎么去解决
`./KikoPlay: relocation error: ./KikoPlay: symbol _ZdlPvm version Qt_5 not defined in file libQt5Core.so.5 with link time reference
`
一直以来想找linux下的弹幕播放器， 找到了但是不能用。 希望作者能帮助我。谢谢。

**Comment by Protostars** [comment]
你直接按照Ubuntu的那些编译步骤试试

**Comment by pureboys** [comment]
> 你直接按照Ubuntu的那些编译步骤试试

环境是manjaro， 对应的命令不一样吧。 完全不懂这块的编译
比如： 
1. 第2,3步 不知道应该对应arch的哪些包
2. 4,5步 如何去做

请大神给教下吧。

**Comment by Protostars** [comment]
> 
> 
> > 你直接按照Ubuntu的那些编译步骤试试
> 
> 环境是manjaro， 对应的命令不一样吧。 完全不懂这块的编译
> 比如：
> 
>     1. 第2,3步 不知道应该对应arch的哪些包
> 
>     2. 4,5步 如何去做
> 
> 
> 请大神给教下吧。

我也没用过这个系统，待我研究一下吧

**Comment by pureboys** [comment]
> > > 你直接按照Ubuntu的那些编译步骤试试
> > 
> > 
> > 环境是manjaro， 对应的命令不一样吧。 完全不懂这块的编译
> > 比如：
> > ```
> > 1. 第2,3步 不知道应该对应arch的哪些包
> > 
> > 2. 4,5步 如何去做
> > ```
> > 
> > 
> > 请大神给教下吧。
> 
> 我也没用过这个系统，待我研究一下吧

感谢大神！

**Comment by Protostars** [comment]
我在虚拟机上试了一下，编译比在ubuntu上还简单
首先安装mpv
之后克隆[QHttpEngine](https://github.com/nitroshare/qhttpengine)
进入qhttpengine目录后编译安装：
`cmake -G "Unix Makefiles"`
`sudo make install`
之后克隆KikoPlay，进入KikoPlay目录后：
`qmake`
`make`
到这里应该就完成编译了
启动：`./KikoPlay`
如果出现找不到libqhttpengine这样的错误，在启动之前添加环境变量：
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`
也可以将/usr/local/lib永久加入LD_LIBRARY_PATH环境变量中
如果要使用下载功能，安装aria2，之后将usr/bin里的aria2c复制到KikoPlay目录下，重新启动KikoPlay
![](https://raw.githubusercontent.com/Protostars/KikoPlay/master/screenshot/KikoPlay-Manjaro.png)

**Comment by pureboys** [comment]
感谢大神！ 编译成功了！
