### ISSUE TITLE
播放几分钟后 自动关闭了

### ISSUE THREAD

**Issue by pureboys** [Protostars/KikoPlay#9]
> Track added:
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (flac 2ch 48000Hz)
 (+) Subs  --sid=1 '[Citrus][09][BDRIP][1080P][H264_FLAC].ass' (ass) (external)
  OpenType support missing for "Bitstream Vera Sans", script 18s+188MB
AV: 00:00:15 / 00:23:41 (1%) A-V:  0.000 Dropped: 29 Cache: 163s+178MB
[sub/ass] fontselect: Using default font family: (方正中雅宋_GBK, 400, 0) -> /usr/share/fonts/TTF/Vera.ttf, 0, BitstreamVeraSans-Roman
[sub/ass] fontselect: Using default font family: (FOT-Matisse ProN B, 400, 0) -> /usr/share/fonts/TTF/Vera.ttf, 0, BitstreamVeraSans-Roman
KikoPlay: ../libdrm-2.4.98/nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.
[1]    4375 abort (core dumped)  ./KikoPlay

**Comment by pureboys** [comment]
> AV: 00:00:31 / 00:23:41 (2%) A-V:  0.000 Dropped: 55 Cache: 147s+159MB
[sub/ass] fontselect: Using default font family: (方正中雅宋_GBK, 400, 0) -> /usr/share/fonts/TTF/Vera.ttf, 0, BitstreamVeraSans-Roman
[sub/ass] fontselect: Using default font family: (FOT-Matisse ProN B, 400, 0) -> /usr/share/fonts/TTF/Vera.ttf, 0, BitstreamVeraSans-Roman
AV: 00:01:34 / 00:23:41 (6%) A-V:  0.000 Dropped: 85 Cache: 180s+159MB
[sub/ass] fontselect: Using default font family: (腾祥嘉丽中圆GB18030, 700, 0) -> /usr/share/fonts/TTF/VeraBd.ttf, 0, BitstreamVeraSans-Bold
[1]    5009 segmentation fault (core dumped)  ./KikoPlayhe: 201s+159MB

**Comment by Protostars** [comment]
找一个没有弹幕的视频播放，看是否会崩溃退出

**Comment by Protostars** [comment]
行了，我看到这一句了
KikoPlay: ../libdrm-2.4.98/nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.
这是linux上的OpenGL驱动不支持多线程导致的。
KikoPlay生成弹幕纹理是在另外的线程，所以会有这个问题
修改kikoplay.pro文件，加上一句：
DEFINES += TEXTURE_MAIN_THREAD
这样会在主线程中创建纹理
之后重新编译
qmake
make

**Comment by pureboys** [comment]
能够正常运行了。感谢大神~
